workspace(name = "multiple_node_versions")

# http_archive(
#     name = "rules_nodejs",
#     sha256 = "a54a01b883beff66da057a1a9afc3be83de566d8ba78f5139f9b370026af5868",
#     urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.0/rules_nodejs-core-4.4.0.tar.gz"],
# )

local_repository(
    name = "rules_nodejs",
    path = "../../../rules_nodejs",
)

local_repository(
    name = "build_bazel_rules_nodejs",
    path = "../../../rules_nodejs",
)

load("@build_bazel_rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains", "rules_nodejs_dependencies")
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories")

# This just gives us bazel-skylib
rules_nodejs_dependencies()

# if changes are made to the order update the tests as the test_node_version_default uses this order
nodejs_register_toolchains(
    name = "node15",
    node_version = "15.14.0",
)

nodejs_register_toolchains(
    name = "node16",
    node_version = "16.9.0",
)

# this should be kept in line with the base workspace node_version as well
node_repositories(
    node_version = "16.5.0",
)
